language: go
go:
- '1.8'
cache:
  directories:
  - tools/bin
script:
- make style
- make web
- CONCURRENT_LINTERS=1 LINTER_DEADLINE=300s make test
- CONCURRENT_LINTERS=1 LINTER_DEADLINE=300s make binary
- tools/bin/goveralls -coverprofile=cover.out -service=travis-ci
